name: Validate SOR metadata

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Normalize metadata
        run: |
          python scripts/normalize_sor_metadata.py
      - name: Validate normalized metadata against schema
        run: |
          python scripts/validate_metadata.py